// Code generated by mockery v2.43.2. DO NOT EDIT.

package Container

import mock "github.com/stretchr/testify/mock"

// iGoFacUUIDWrapper is an autogenerated mock type for the iGoFacUUIDWrapper type
type iGoFacUUIDWrapper struct {
	mock.Mock
}

type iGoFacUUIDWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *iGoFacUUIDWrapper) EXPECT() *iGoFacUUIDWrapper_Expecter {
	return &iGoFacUUIDWrapper_Expecter{mock: &_m.Mock}
}

// getContextID provides a mock function with given fields:
func (_m *iGoFacUUIDWrapper) getContextID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getContextID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// iGoFacUUIDWrapper_getContextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getContextID'
type iGoFacUUIDWrapper_getContextID_Call struct {
	*mock.Call
}

// getContextID is a helper method to define mock.On call
func (_e *iGoFacUUIDWrapper_Expecter) getContextID() *iGoFacUUIDWrapper_getContextID_Call {
	return &iGoFacUUIDWrapper_getContextID_Call{Call: _e.mock.On("getContextID")}
}

func (_c *iGoFacUUIDWrapper_getContextID_Call) Run(run func()) *iGoFacUUIDWrapper_getContextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *iGoFacUUIDWrapper_getContextID_Call) Return(_a0 string) *iGoFacUUIDWrapper_getContextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *iGoFacUUIDWrapper_getContextID_Call) RunAndReturn(run func() string) *iGoFacUUIDWrapper_getContextID_Call {
	_c.Call.Return(run)
	return _c
}

// newIGoFacUUIDWrapper creates a new instance of iGoFacUUIDWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIGoFacUUIDWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *iGoFacUUIDWrapper {
	mock := &iGoFacUUIDWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
