// Code generated by mockery v2.43.2. DO NOT EDIT.

package interfaces

import (
	context "context"

	Registration "github.com/TaBSRest/GoFac/internal/Registration"

	mock "github.com/stretchr/testify/mock"

	reflect "reflect"

	sync "sync"
)

// Container is an autogenerated mock type for the Container type
type Container struct {
	mock.Mock
}

type Container_Expecter struct {
	mock *mock.Mock
}

func (_m *Container) EXPECT() *Container_Expecter {
	return &Container_Expecter{mock: &_m.Mock}
}

// GetGroupedRegistrations provides a mock function with given fields: name
func (_m *Container) GetGroupedRegistrations(name string) ([]*Registration.Registration, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupedRegistrations")
	}

	var r0 []*Registration.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*Registration.Registration, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []*Registration.Registration); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Registration.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Container_GetGroupedRegistrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupedRegistrations'
type Container_GetGroupedRegistrations_Call struct {
	*mock.Call
}

// GetGroupedRegistrations is a helper method to define mock.On call
//   - name string
func (_e *Container_Expecter) GetGroupedRegistrations(name interface{}) *Container_GetGroupedRegistrations_Call {
	return &Container_GetGroupedRegistrations_Call{Call: _e.mock.On("GetGroupedRegistrations", name)}
}

func (_c *Container_GetGroupedRegistrations_Call) Run(run func(name string)) *Container_GetGroupedRegistrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Container_GetGroupedRegistrations_Call) Return(_a0 []*Registration.Registration, _a1 error) *Container_GetGroupedRegistrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Container_GetGroupedRegistrations_Call) RunAndReturn(run func(string) ([]*Registration.Registration, error)) *Container_GetGroupedRegistrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamedRegistration provides a mock function with given fields: name
func (_m *Container) GetNamedRegistration(name string) (*Registration.Registration, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNamedRegistration")
	}

	var r0 *Registration.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Registration.Registration, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *Registration.Registration); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Registration.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Container_GetNamedRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamedRegistration'
type Container_GetNamedRegistration_Call struct {
	*mock.Call
}

// GetNamedRegistration is a helper method to define mock.On call
//   - name string
func (_e *Container_Expecter) GetNamedRegistration(name interface{}) *Container_GetNamedRegistration_Call {
	return &Container_GetNamedRegistration_Call{Call: _e.mock.On("GetNamedRegistration", name)}
}

func (_c *Container_GetNamedRegistration_Call) Run(run func(name string)) *Container_GetNamedRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Container_GetNamedRegistration_Call) Return(_a0 *Registration.Registration, _a1 error) *Container_GetNamedRegistration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Container_GetNamedRegistration_Call) RunAndReturn(run func(string) (*Registration.Registration, error)) *Container_GetNamedRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// GetPerContextRegistrations provides a mock function with given fields:
func (_m *Container) GetPerContextRegistrations() []*Registration.Registration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPerContextRegistrations")
	}

	var r0 []*Registration.Registration
	if rf, ok := ret.Get(0).(func() []*Registration.Registration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Registration.Registration)
		}
	}

	return r0
}

// Container_GetPerContextRegistrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPerContextRegistrations'
type Container_GetPerContextRegistrations_Call struct {
	*mock.Call
}

// GetPerContextRegistrations is a helper method to define mock.On call
func (_e *Container_Expecter) GetPerContextRegistrations() *Container_GetPerContextRegistrations_Call {
	return &Container_GetPerContextRegistrations_Call{Call: _e.mock.On("GetPerContextRegistrations")}
}

func (_c *Container_GetPerContextRegistrations_Call) Run(run func()) *Container_GetPerContextRegistrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_GetPerContextRegistrations_Call) Return(_a0 []*Registration.Registration) *Container_GetPerContextRegistrations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Container_GetPerContextRegistrations_Call) RunAndReturn(run func() []*Registration.Registration) *Container_GetPerContextRegistrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistrationsFor provides a mock function with given fields: registrationType
func (_m *Container) GetRegistrationsFor(registrationType reflect.Type) ([]*Registration.Registration, bool) {
	ret := _m.Called(registrationType)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistrationsFor")
	}

	var r0 []*Registration.Registration
	var r1 bool
	if rf, ok := ret.Get(0).(func(reflect.Type) ([]*Registration.Registration, bool)); ok {
		return rf(registrationType)
	}
	if rf, ok := ret.Get(0).(func(reflect.Type) []*Registration.Registration); ok {
		r0 = rf(registrationType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Registration.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(reflect.Type) bool); ok {
		r1 = rf(registrationType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Container_GetRegistrationsFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistrationsFor'
type Container_GetRegistrationsFor_Call struct {
	*mock.Call
}

// GetRegistrationsFor is a helper method to define mock.On call
//   - registrationType reflect.Type
func (_e *Container_Expecter) GetRegistrationsFor(registrationType interface{}) *Container_GetRegistrationsFor_Call {
	return &Container_GetRegistrationsFor_Call{Call: _e.mock.On("GetRegistrationsFor", registrationType)}
}

func (_c *Container_GetRegistrationsFor_Call) Run(run func(registrationType reflect.Type)) *Container_GetRegistrationsFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Type))
	})
	return _c
}

func (_c *Container_GetRegistrationsFor_Call) Return(_a0 []*Registration.Registration, _a1 bool) *Container_GetRegistrationsFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Container_GetRegistrationsFor_Call) RunAndReturn(run func(reflect.Type) ([]*Registration.Registration, bool)) *Container_GetRegistrationsFor_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingletonCache provides a mock function with given fields:
func (_m *Container) GetSingletonCache() *sync.Map {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSingletonCache")
	}

	var r0 *sync.Map
	if rf, ok := ret.Get(0).(func() *sync.Map); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.Map)
		}
	}

	return r0
}

// Container_GetSingletonCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingletonCache'
type Container_GetSingletonCache_Call struct {
	*mock.Call
}

// GetSingletonCache is a helper method to define mock.On call
func (_e *Container_Expecter) GetSingletonCache() *Container_GetSingletonCache_Call {
	return &Container_GetSingletonCache_Call{Call: _e.mock.On("GetSingletonCache")}
}

func (_c *Container_GetSingletonCache_Call) Run(run func()) *Container_GetSingletonCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_GetSingletonCache_Call) Return(_a0 *sync.Map) *Container_GetSingletonCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Container_GetSingletonCache_Call) RunAndReturn(run func() *sync.Map) *Container_GetSingletonCache_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterContext provides a mock function with given fields: _a0
func (_m *Container) RegisterContext(_a0 context.Context) context.Context {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RegisterContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Container_RegisterContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterContext'
type Container_RegisterContext_Call struct {
	*mock.Call
}

// RegisterContext is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Container_Expecter) RegisterContext(_a0 interface{}) *Container_RegisterContext_Call {
	return &Container_RegisterContext_Call{Call: _e.mock.On("RegisterContext", _a0)}
}

func (_c *Container_RegisterContext_Call) Run(run func(_a0 context.Context)) *Container_RegisterContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Container_RegisterContext_Call) Return(_a0 context.Context) *Container_RegisterContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Container_RegisterContext_Call) RunAndReturn(run func(context.Context) context.Context) *Container_RegisterContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainer creates a new instance of Container. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Container {
	mock := &Container{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
