// Code generated by mockery v2.43.2. DO NOT EDIT.

package Interfaces

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// UUIDProvider is an autogenerated mock type for the UUIDProvider type
type UUIDProvider struct {
	mock.Mock
}

type UUIDProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UUIDProvider) EXPECT() *UUIDProvider_Expecter {
	return &UUIDProvider_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields:
func (_m *UUIDProvider) New() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// UUIDProvider_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type UUIDProvider_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *UUIDProvider_Expecter) New() *UUIDProvider_New_Call {
	return &UUIDProvider_New_Call{Call: _e.mock.On("New")}
}

func (_c *UUIDProvider_New_Call) Run(run func()) *UUIDProvider_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UUIDProvider_New_Call) Return(_a0 uuid.UUID) *UUIDProvider_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UUIDProvider_New_Call) RunAndReturn(run func() uuid.UUID) *UUIDProvider_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewUUIDProvider creates a new instance of UUIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUUIDProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UUIDProvider {
	mock := &UUIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
