// Code generated by mockery v2.43.2. DO NOT EDIT.

package SampleStructs

import mock "github.com/stretchr/testify/mock"

// IIndependentStruct2 is an autogenerated mock type for the IIndependentStruct2 type
type IIndependentStruct2 struct {
	mock.Mock
}

type IIndependentStruct2_Expecter struct {
	mock *mock.Mock
}

func (_m *IIndependentStruct2) EXPECT() *IIndependentStruct2_Expecter {
	return &IIndependentStruct2_Expecter{mock: &_m.Mock}
}

// ReturnNameIndependentStruct provides a mock function with given fields:
func (_m *IIndependentStruct2) ReturnNameIndependentStruct() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReturnNameIndependentStruct")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IIndependentStruct2_ReturnNameIndependentStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnNameIndependentStruct'
type IIndependentStruct2_ReturnNameIndependentStruct_Call struct {
	*mock.Call
}

// ReturnNameIndependentStruct is a helper method to define mock.On call
func (_e *IIndependentStruct2_Expecter) ReturnNameIndependentStruct() *IIndependentStruct2_ReturnNameIndependentStruct_Call {
	return &IIndependentStruct2_ReturnNameIndependentStruct_Call{Call: _e.mock.On("ReturnNameIndependentStruct")}
}

func (_c *IIndependentStruct2_ReturnNameIndependentStruct_Call) Run(run func()) *IIndependentStruct2_ReturnNameIndependentStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IIndependentStruct2_ReturnNameIndependentStruct_Call) Return(_a0 string) *IIndependentStruct2_ReturnNameIndependentStruct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IIndependentStruct2_ReturnNameIndependentStruct_Call) RunAndReturn(run func() string) *IIndependentStruct2_ReturnNameIndependentStruct_Call {
	_c.Call.Return(run)
	return _c
}

// NewIIndependentStruct2 creates a new instance of IIndependentStruct2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIIndependentStruct2(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIndependentStruct2 {
	mock := &IIndependentStruct2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
