// Code generated by mockery v2.43.2. DO NOT EDIT.

package SampleStructs

import mock "github.com/stretchr/testify/mock"

// IStructRelyingOnIndependentStructBase is an autogenerated mock type for the IStructRelyingOnIndependentStructBase type
type IStructRelyingOnIndependentStructBase struct {
	mock.Mock
}

type IStructRelyingOnIndependentStructBase_Expecter struct {
	mock *mock.Mock
}

func (_m *IStructRelyingOnIndependentStructBase) EXPECT() *IStructRelyingOnIndependentStructBase_Expecter {
	return &IStructRelyingOnIndependentStructBase_Expecter{mock: &_m.Mock}
}

// ReturnNameStructRelyingOnIndependentStruct provides a mock function with given fields:
func (_m *IStructRelyingOnIndependentStructBase) ReturnNameStructRelyingOnIndependentStruct() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReturnNameStructRelyingOnIndependentStruct")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnNameStructRelyingOnIndependentStruct'
type IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call struct {
	*mock.Call
}

// ReturnNameStructRelyingOnIndependentStruct is a helper method to define mock.On call
func (_e *IStructRelyingOnIndependentStructBase_Expecter) ReturnNameStructRelyingOnIndependentStruct() *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call {
	return &IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call{Call: _e.mock.On("ReturnNameStructRelyingOnIndependentStruct")}
}

func (_c *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call) Run(run func()) *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call) Return(_a0 string) *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call) RunAndReturn(run func() string) *IStructRelyingOnIndependentStructBase_ReturnNameStructRelyingOnIndependentStruct_Call {
	_c.Call.Return(run)
	return _c
}

// NewIStructRelyingOnIndependentStructBase creates a new instance of IStructRelyingOnIndependentStructBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStructRelyingOnIndependentStructBase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStructRelyingOnIndependentStructBase {
	mock := &IStructRelyingOnIndependentStructBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
